<?xml version="1.0" ?>
<robot name='robot' xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="$(find my_robot)/urdf/robot.gazebo.xacro" />

    <xacro:property name="chassis_length" value="0.15"/>
    <xacro:property name="chassis_width" value="0.13"/>
    <xacro:property name="chassis_height" value="0.07"/>

    <xacro:property name="wheel_radius" value="0.033"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.05"/>

    <xacro:property name="wheel_offset_x" value="0.1"/>
    <xacro:property name="wheel_offset_y" value="0.07"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>

    <xacro:property name="caster_wheel_radius" value="0.02"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.02"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>
    <xacro:property name="mass" value="1.0"/>
    <xacro:property name="M_PI" value="3.1415926535897931"/>

    <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
    </material>

    <material name="Gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
    </material>

    <link name="base_link">
    </link>

    <link name="base_footprint">
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 -0.138" rpy="0 0 0"/>
    </joint>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name='chassis'>
        <inertial>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (chassis_width*chassis_width+chassis_height*chassis_height)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * mass * (chassis_length*chassis_length+chassis_height*chassis_height)}" iyz="0.0"
                     izz="${(1/12) * mass * (chassis_length*chassis_length+chassis_width*chassis_width)}" />
        </inertial>
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="Cyan"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
    </link>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${M_PI/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="Gray"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}" />
            <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0.0"
                     izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}" />
        </inertial>
    </link>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${M_PI/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="Gray"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}" />
            <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0.0"
                     izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}" />
        </inertial>
    </link>

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="Cyan"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${caster_wheel_mass}" />
            <inertia ixx="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" ixy="0.0" ixz="0.0"
                     iyy="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" iyz="0.0"
                     izz="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" />
        </inertial>
    </link>

    <gazebo reference="caster_wheel">
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <!-- ANTENNA -->
    <link name="antenna_base">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.005" length="0.08"/>
            </geometry>
            <material name="Gray"/>
        </visual>
    </link>

    <joint name="antenna_base_joint" type="fixed">
        <parent link="chassis"/>
        <child link="antenna_base"/>
        <origin xyz="0 0 ${chassis_height/2 + 0.04}" rpy="0 0 0"/>
    </joint>

    <link name="antenna_tip">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <sphere radius="0.012"/>
            </geometry>
            <material name="Cyan"/>
        </visual>
    </link>

    <joint name="antenna_tip_joint" type="fixed">
        <parent link="antenna_base"/>
        <child link="antenna_tip"/>
        <origin xyz="0 0 0.04" rpy="0 0 0"/>
    </joint>

    <!-- Sensors -->
    <gazebo reference="antenna_tip">
        <sensor name="gpu_lidar" type="gpu_lidar">
            <always_on>true</always_on>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <topic>/scan</topic>
            <frame_id>antenna_tip</frame_id> 
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-${M_PI}</min_angle>
                        <max_angle>${M_PI}</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.08</min>
                    <max>10.0</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
        </sensor>
    </gazebo>

    <link name="depth_frame">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.12 0.02"/>
            </geometry>
            <material name="Gray"/>
        </visual>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.001"/>
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0" 
                     iyy="0.0001" iyz="0.0" 
                     izz="0.0001"/>
        </inertial>
    </link>

    <joint name="depth_joint" type="fixed">
        <parent link="base_link"/>
        <child link="depth_frame"/>
        <origin xyz="0.04 0 0.07" rpy="0 0 0"/>
    </joint>

    <gazebo reference="depth_frame">
        <sensor name="depth_camera" type="depth_camera">
            <!-- <gz_frame_id>robot/depth_frame</gz_frame_id> -->
            <pose>0 0 0 0 0 0</pose>
            <always_on>true</always_on>
            <update_rate>10</update_rate>
            <camera>
                <horizontal_fov>1.51843645</horizontal_fov>
                <image>
                    <width>848</width>
                    <height>480</height>
                    <format>R_FLOAT32</format>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>10</far>
                </clip>
                <lens>
                    <intrinsics>
                        <fx>421.61578369140625</fx>
                        <fy>421.61578369140625</fy>
                        <cx>422.2854309082031</cx>
                        <cy>236.57237243652344</cy>
                        <s>0</s>
                    </intrinsics>
                </lens>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
            </camera>
        </sensor>
    </gazebo>

    <link name="imu_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
            <material name="Gray"/>
        </visual>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.001"/>
            <inertia ixx="0.000166667" ixy="0.0" ixz="0.0" 
                    iyy="0.000166667" iyz="0.0" 
                    izz="0.000166667"/>
        </inertial>
    </link>

    <joint name="imu_joint" type="fixed">
        <parent link="chassis"/>
        <child link="imu_link"/>
        <origin xyz="0 0 0.03" rpy="0 0 0"/>
    </joint>

    <gazebo reference="imu_link">
        <sensor name="imu_sensor" type="imu">
            <pose>0 0 0 0 0 0</pose>
            <always_on>1</always_on>
            <update_rate>100</update_rate>
            <visualize>true</visualize>
            <topic>imu</topic>
            <!-- <gz_frame_id>imu_link</gz_frame_id> -->

        </sensor>
    </gazebo>
</robot>
